export type Language = 'fr' | 'en' | 'es'

const fr = {
  bobCommands: 'Commandes Bob', addToPrompt: 'Ajouter au prompt',
  appName: 'Bob Mobile', disconnected: 'Déconnecté', connectTitle: 'Connecter Bob Work', connectDesc: 'Dans Bob Work, ouvrez Réglages → Télécommande, activez-la puis copiez le lien Cloudflare.',
  connectionLink: 'Lien de connexion', connectionPlaceholder: 'Collez le lien sécurisé Bob Work', connect: 'Se connecter', connecting: 'Connexion…', invalidLink: 'Ce lien de connexion est invalide.', missingToken: 'Le lien ne contient pas de jeton d’accès.', connectionFailed: 'Impossible de joindre Bob Work.', connectionTimeout: 'Bob Work ne répond pas. La tentative a été arrêtée après 10 secondes.', apiUnavailable: 'Le tunnel répond, mais l’API Bob Work n’est pas disponible.', connectionExpired: 'Ce lien a expiré ou son jeton a été révoqué. Copiez le lien actuel depuis Bob Work.', updateConnection: 'Nouveau lien',
  conversations: 'Conversations', projects: 'Projets', activity: 'Activité', files: 'Fichiers', settings: 'Réglages', newConversation: 'Nouvelle conversation', noConversations: 'Aucune conversation', noConversationsDesc: 'Créez une conversation pour commencer à piloter Bob Work.', syncRequiredTitle: 'Reconnectez Bob Work', syncRequiredDesc: 'L’historique sera rechargé directement depuis la base SQLite du Mac après reconnexion.', searchConversations: 'Rechercher dans l’historique', history: 'Historique', syncUnavailable: 'Synchronisation momentanément indisponible — toucher pour réessayer.',
  allProjects: 'Tous les projets', noProject: 'Sans projet', conversationTitle: 'Titre', conversationTitlePlaceholder: 'Nouvelle conversation', create: 'Créer', cancel: 'Annuler', active: 'En cours', queued: 'En attente', refresh: 'Actualiser',
  recent: 'Récentes', completed: 'Terminées', scheduled: 'Planifiées', archived: 'Archivées', archivedChats: 'Chats archivés', archivedChatsDescription: 'Les chats archivés sont gérés ici sans pouvoir être consultés.', noArchivedChats: 'Aucun chat archivé.', archivedChatsLoadFailed: 'Impossible de charger les chats archivés.', archive: 'Archiver', restore: 'Restaurer', pin: 'Épingler', unpin: 'Désépingler', moreActions: 'Plus d’actions', conversationActions: 'Gérer la conversation', moveToProject: 'Déplacer vers un projet', saveChanges: 'Enregistrer', delete: 'Supprimer', deleteConversation: 'Supprimer la conversation', deleteConversationConfirm: 'Supprimer définitivement cette conversation de Bob Work ?', conversationUpdateFailed: 'La conversation n’a pas pu être modifiée.', conversationDeleteFailed: 'La conversation n’a pas pu être supprimée.',
  newProject: 'Nouveau projet', editProject: 'Modifier le projet', openProject: 'Ouvrir le projet', projectName: 'Nom du projet', projectNamePlaceholder: 'Ex. Refonte du site', description: 'Description', descriptionPlaceholder: 'Contexte du projet', objective: 'Objectif', objectivePlaceholder: 'Résultat attendu', customInstructions: 'Instructions du projet', customInstructionsPlaceholder: 'Règles et contexte propres à ce projet', projectLanguage: 'Langue du projet', automatic: 'Automatique', memory: 'Mémoire du projet', memoryOn: 'Activée', memoryOff: 'Désactivée', defaultMode: 'Mode par défaut', integrations: 'Intégrations', noProjects: 'Aucun projet', noProjectsDesc: 'Créez votre premier projet Bob Work.', openConversations: 'Voir les conversations', conversationsCount: '{{count}} conversation(s)', activeTasksCount: '{{count}} tâche(s) active(s)', emptySelectionAllowsAll: 'Sans sélection, tous les éléments installés sont autorisés.', projectUpdated: 'Projet mis à jour', projectUpdateFailed: 'Le projet n’a pas pu être modifié.', deleteProject: 'Supprimer le projet', deleteProjectConfirm: 'Supprimer définitivement ce projet de Bob Work ?', projectDeleteFailed: 'Le projet n’a pas pu être supprimé.', startProjectConversation: 'Démarrer une conversation', recentTasks: 'Tâches du projet', projectFiles: 'Fichiers du projet', allowedResources: 'Autorisations du projet', allAllowed: 'Tout autoriser', untitledTask: 'Tâche sans titre',
  pluginsAndSkills: 'Plugins et skills', plugins: 'Plugins', skills: 'Skills', selectedPlugins: 'Plugins sélectionnés', removePlugin: 'Retirer {{name}}', selectedCount: '{{count}} sélectionné(s)', noneSelected: 'Aucun sélectionné', done: 'Terminé', mode: 'Mode', modeAgent: 'Agent', modePlan: 'Planification', modeAsk: 'Question', scheduleActive: 'Actif',
  searchCatalog: 'Rechercher un skill, plugin ou intégration…', noPlugins: 'Aucun plugin activé.', noSkills: 'Aucun skill activé.', noIntegrations: 'Aucune intégration connectée.', noPluginMatch: 'Aucun plugin correspondant.', noSkillMatch: 'Aucun skill correspondant.', noIntegrationMatch: 'Aucune intégration correspondante.', noModeMatch: 'Aucun mode correspondant.', integrationConnected: 'Connectée', integrationDisconnected: 'Non connectée',
  promptPlaceholder: 'Demandez quelque chose à Bob…', send: 'Envoyer', attach: 'Ajouter', attachment: 'Pièce jointe', attachFile: 'Fichier', attachPhoto: 'Photo', attachments: 'Pièces jointes', artifacts: 'Fichiers créés', interactiveVisualization: 'Visualisation interactive', openPreview: 'Ouvrir l’aperçu', fileChanges: 'Fichiers modifiés', fileCreated: 'Créé', fileModified: 'Modifié', fileDeleted: 'Supprimé', openOrDownload: 'Ouvrir ou télécharger', download: 'Télécharger', downloadComplete: 'Fichier prêt à être enregistré ou partagé.', artifactFailed: 'Impossible de récupérer ce fichier.', remove: 'Retirer', tools: 'Outils', you: 'Vous',
  filesCount: '{{count}} fichier(s)', searchFiles: 'Rechercher un fichier', allFiles: 'Tous', images: 'Images', textFiles: 'Texte', otherFiles: 'Autres', noFiles: 'Aucun fichier', noFilesDesc: 'Les documents créés par Bob apparaîtront ici, quelle que soit leur conversation.', filesLoadFailed: 'Impossible de charger les fichiers de Bob Work.', deleteFile: 'Supprimer le fichier', deleteFileConfirm: 'Supprimer définitivement « {{name}} » de Bob Work ?', fileDeleteFailed: 'Le fichier n’a pas pu être supprimé.', saveOrShare: 'Enregistrer ou partager', originProject: 'Projet', originConversation: 'Conversation', valid: 'Valide', warning: 'Avertissement', invalid: 'Invalide', pending: 'À valider', systemPreviewHint: 'Utilisez le bouton ci-dessous pour l’ouvrir dans le lecteur iOS ou l’enregistrer dans Fichiers.', loading: 'Chargement…',
  loadingOlder: 'Chargement des échanges précédents…', loadingMoreHistory: 'Chargement de la suite…', noMessages: 'Envoyez votre premier prompt.', bobWorking: 'Bob travaille…', projectToolsRestricted: 'Outils limités par le projet', allToolsAvailable: 'Tous les outils installés sont disponibles', sendFailed: 'Le prompt n’a pas pu être envoyé.', uploadFailed: 'Cette pièce jointe n’a pas pu être préparée.', imagePermission: 'Autorisez l’accès aux photos pour joindre une photo.',
  editPrompt: 'Modifier', editingPrompt: 'Modification du prompt', resendPrompt: 'Renvoyer', cancelEdit: 'Annuler la modification', copyMarkdown: 'Copier', copied: 'Markdown copié', shareResponse: 'Partager', promptQueue: 'File d’attente', queuedPrompts: '{{count}} prompt(s) en attente', promptQueued: 'Prompt ajouté à la file', clearQueue: 'Vider', moveUp: 'Monter', moveDown: 'Descendre',
  noTasks: 'Aucune activité', noTasksDesc: 'Les tâches lancées dans Bob Work apparaîtront ici.', taskStarting: 'Démarrage', taskRunning: 'En cours', taskQueued: 'En attente', taskApproval: 'Autorisation requise', taskPaused: 'En pause', taskCompleted: 'Terminée', taskFailed: 'Échouée', taskCancelled: 'Annulée', taskExpired: 'Expirée', taskDraft: 'Brouillon', riskLow: 'Faible', riskMedium: 'Moyen', riskHigh: 'Élevé', riskCritical: 'Critique', eventAnalysis: 'Analyse en cours', eventContent: 'Contenu produit', eventError: 'Erreur', eventHookStarted: 'Préparation', eventMessageStarted: 'Réponse en cours', eventMessageFinished: 'Réponse terminée', eventRunFinished: 'Exécution terminée', eventText: 'Texte généré', eventToolStarted: 'Outil démarré', eventToolProgress: 'Outil en cours', eventToolFinished: 'Outil terminé', eventUsage: 'Utilisation', eventTaskStarted: 'Tâche démarrée', eventTaskCompleted: 'Tâche terminée', eventTaskFailed: 'Tâche échouée', eventSubagentStarted: 'Sous-agent démarré', eventSubagentFinished: 'Sous-agent terminé', subagentsRunning: '{{count}} sous-agent(s) en cours', subagents: '{{count}} sous-agent(s)', subagentFallback: 'Sous-agent', subagentRunning: 'En cours', subagentCompleted: 'Terminé', subagentFailed: 'Échec', subagentCancelled: 'Arrêté',
  tasksTab: 'Tâches', automationsTab: 'Planifié', taskDetails: 'Détails de la tâche', taskResult: 'Résultat', taskErrors: 'Erreurs', taskTools: 'Outils utilisés', taskRuns: 'Historique des exécutions', duration: 'Durée', pinTask: 'Épingler la tâche', unpinTask: 'Désépingler la tâche', noResult: 'Aucun résultat disponible.', newAutomation: 'Nouvelle planification', noAutomations: 'Aucune planification', noAutomationsDesc: 'Planifiez une tâche récurrente exécutée par Bob Work.', automationName: 'Nom', automationInstructions: 'Instructions', frequency: 'Fréquence', everyDay: 'Chaque jour', everyWeek: 'Chaque semaine', everyMonth: 'Chaque mois', runAt: 'Heure', createAutomation: 'Créer la planification', pauseAutomation: 'Mettre en pause', resumeAutomation: 'Réactiver', runNow: 'Exécuter maintenant', runHistory: 'Historique', nextRun: 'Prochaine exécution : {{date}}', neverRun: 'Jamais exécutée', noRuns: 'Aucune exécution', automationCreated: 'Planification créée', automationFailed: 'Impossible de mettre à jour cette planification.',
  liveConnected: 'Temps réel actif', liveDisconnected: 'Reconnexion au temps réel…', taskActivity: 'Activité en direct', noActivityYet: 'Bob prépare la tâche…', stopTask: 'Arrêter', stopTaskConfirm: 'Arrêter cette tâche sur le Mac ?', stopFailed: 'Impossible d’arrêter cette tâche.', approvals: 'Autorisations', approveOnce: 'Autoriser une fois', approveTask: 'Pour cette tâche', approveAlways: 'Toujours autoriser', deny: 'Refuser', approvalFailed: 'Impossible d’enregistrer cette décision.', risk: 'Risque : {{level}}', retryTask: 'Relancer', retryTaskConfirm: 'Relancer cette tâche avec Bob ?', retryFailed: 'La tâche n’a pas pu être relancée.', taskAwaitingInfo: 'Réponse nécessaire', notificationTaskDone: 'Tâche terminée', notificationTaskFailed: 'Tâche échouée', notificationApproval: 'Autorisation demandée', viewDetails: 'Voir les détails',
  currentLocation: 'Position actuelle', currentLocationDesc: 'Utiliser ma position pour les recherches proches et comme départ d’itinéraire.', locationEnabled: 'Position autorisée', locationDisabled: 'Position désactivée', locationRefresh: 'Actualiser', locationPermissionDenied: 'Autorisez la localisation dans les réglages du téléphone.', locationUpdateFailed: 'La position n’a pas pu être transmise à Bob Work.', locationPrivacy: 'La position est envoyée uniquement à votre Bob Work connecté et utilisée pour une demande cartographique pertinente.',
  remoteConnection: 'Connexion distante', connected: 'Connecté', server: 'Serveur', language: 'Langue', bobStatus: 'État de Bob Work', bobAvailable: 'Bob Shell disponible', bobUnavailable: 'Bob Shell indisponible', workspaceSettings: 'Configuration Bob Work', syncStatus: 'Synchronisation', lastSync: 'Dernière mise à jour : {{date}}', bobcoins: 'Bobcoins', bobcoinsUsed: '{{used}} / {{total}} utilisés', bobcoinsRemaining: '{{remaining}} restants', bobcoinsUnavailable: 'Consommation indisponible', bobcoinsUpdated: 'Mis à jour : {{date}}', sandboxOn: 'Bac à sable activé', sandboxOff: 'Accès standard au projet', permissionPolicy: 'Politique d’autorisation', policyAlwaysAsk: 'Toujours demander', policyAskImportant: 'Demander pour les actions importantes', policyAskModifications: 'Demander avant les modifications', policyNeverAsk: 'Ne jamais demander', followsBobWork: 'Les modes, projets et règles d’exécution proviennent de ce Mac.', disconnect: 'Déconnecter', disconnectConfirm: 'Déconnecter Bob Mobile de ce Mac ?', confirm: 'Confirmer', back: 'Retour', retry: 'Réessayer', error: 'Erreur',
  extensions: 'Extensions', manageExtensions: 'Plugins, skills et intégrations', extensionsDescription: 'Gérez les capacités installées sur ce Mac.', integrated: 'Intégrés', personal: 'Personnels', favorites: 'Favoris', recentlyUsed: 'Récents', all: 'Tous', enabled: 'Activé', disabled: 'Désactivé', enable: 'Activer', disable: 'Désactiver', pluginDetails: 'Détails du plugin', skillDetails: 'Détails du skill', integrationDetails: 'Détails de l’intégration', permissions: 'Autorisations', capabilities: 'Capacités', toolsAvailable: 'Outils disponibles', configurationOnMac: 'Configuration sur le Mac', configurationOnMacDesc: 'Les clés API, comptes et installations sensibles restent protégés dans Bob Work sur le Mac.', configuredOnMac: 'Configurée sur le Mac', requiresConfiguration: 'À configurer sur le Mac', noPermissions: 'Aucune autorisation supplémentaire.', noTools: 'Aucun outil déclaré.', version: 'Version {{version}}', updateAvailable: 'Version {{version}} disponible', updatePlugin: 'Mettre à jour', updating: 'Mise à jour…', pluginUpdated: 'Plugin mis à jour', extensionUpdateFailed: 'La mise à jour n’a pas pu être installée.', extensionLoadFailed: 'Impossible de charger les extensions de Bob Work.', addFavorite: 'Ajouter aux favoris', removeFavorite: 'Retirer des favoris', scope: 'Portée', connectedAccount: 'Compte : {{account}}', oauthReady: 'Connexion disponible sur le Mac', scopeMissing: 'Autorisations du compte incomplètes', sensitiveOnMac: 'La connexion et la saisie des secrets se font uniquement sur le Mac.', lastUsed: 'Dernière utilisation : {{date}}', neverUsed: 'Pas encore utilisé', noCatalogResults: 'Aucun élément correspondant.', pluginActivationFailed: 'L’état du plugin n’a pas pu être modifié.', skillActivationFailed: 'L’état du skill n’a pas pu être modifié.', builtinItem: 'Intégré', personalItem: 'Personnel',
  mcpAndApis: 'MCP et APIs', noMcpAndApis: 'Aucun serveur MCP ou API configuré.', databases: 'Bases de données', noDatabases: 'Aucune base de données configurée.', microphonePermissionTitle: 'Microphone requis', microphonePermission: 'Autorisez Bob Mobile à utiliser le microphone pour enregistrer un prompt.', recordingFailed: 'L’enregistrement audio a échoué.', voicePromptFallback: 'Analyse ce message vocal et réponds à ma demande.', attachmentPromptFallback: 'Analyse les pièces jointes et réponds à ma demande.', voiceRecording: 'Message vocal', stopRecording: 'Arrêter l’enregistrement', recordVoice: 'Enregistrer un message vocal', recording: 'Enregistrement', selectedResources: '{{count}} ressource(s) sélectionnée(s)', importFile: 'Importer un fichier',
  french: 'Français', english: 'English', spanish: 'Español', secureStorage: 'Le jeton est conservé dans le stockage sécurisé de l’appareil.', projectCreated: 'Projet créé', projectCreateFailed: 'Impossible de créer le projet.', conversationCreateFailed: 'Impossible de créer la conversation.',
}

const en: typeof fr = {
  bobCommands: 'Bob commands', addToPrompt: 'Add to prompt',
  appName: 'Bob Mobile', disconnected: 'Disconnected', connectTitle: 'Connect Bob Work', connectDesc: 'In Bob Work, open Settings → Remote control, enable it, then copy the Cloudflare link.',
  connectionLink: 'Connection link', connectionPlaceholder: 'Paste the secure Bob Work link', connect: 'Connect', connecting: 'Connecting…', invalidLink: 'This connection link is invalid.', missingToken: 'The link does not contain an access token.', connectionFailed: 'Could not reach Bob Work.', connectionTimeout: 'Bob Work did not respond. The attempt was stopped after 10 seconds.', apiUnavailable: 'The tunnel responds, but the Bob Work API is unavailable.', connectionExpired: 'This link has expired or its token was revoked. Copy the current link from Bob Work.', updateConnection: 'New link',
  conversations: 'Conversations', projects: 'Projects', activity: 'Activity', files: 'Files', settings: 'Settings', newConversation: 'New conversation', noConversations: 'No conversations', noConversationsDesc: 'Create a conversation to start controlling Bob Work.', syncRequiredTitle: 'Reconnect Bob Work', syncRequiredDesc: 'History will reload directly from the Mac SQLite database after reconnection.', searchConversations: 'Search conversation history', history: 'History', syncUnavailable: 'Sync is temporarily unavailable — tap to retry.',
  allProjects: 'All projects', noProject: 'No project', conversationTitle: 'Title', conversationTitlePlaceholder: 'New conversation', create: 'Create', cancel: 'Cancel', active: 'Running', queued: 'Queued', refresh: 'Refresh',
  recent: 'Recent', completed: 'Completed', scheduled: 'Scheduled', archived: 'Archived', archivedChats: 'Archived chats', archivedChatsDescription: 'Archived chats can be managed here but cannot be opened.', noArchivedChats: 'No archived chats.', archivedChatsLoadFailed: 'Could not load archived chats.', archive: 'Archive', restore: 'Restore', pin: 'Pin', unpin: 'Unpin', moreActions: 'More actions', conversationActions: 'Manage conversation', moveToProject: 'Move to project', saveChanges: 'Save changes', delete: 'Delete', deleteConversation: 'Delete conversation', deleteConversationConfirm: 'Permanently delete this conversation from Bob Work?', conversationUpdateFailed: 'The conversation could not be updated.', conversationDeleteFailed: 'The conversation could not be deleted.',
  newProject: 'New project', editProject: 'Edit project', openProject: 'Open project', projectName: 'Project name', projectNamePlaceholder: 'E.g. Website redesign', description: 'Description', descriptionPlaceholder: 'Project context', objective: 'Objective', objectivePlaceholder: 'Expected outcome', customInstructions: 'Project instructions', customInstructionsPlaceholder: 'Rules and context specific to this project', projectLanguage: 'Project language', automatic: 'Automatic', memory: 'Project memory', memoryOn: 'Enabled', memoryOff: 'Disabled', defaultMode: 'Default mode', integrations: 'Integrations', noProjects: 'No projects', noProjectsDesc: 'Create your first Bob Work project.', openConversations: 'View conversations', conversationsCount: '{{count}} conversation(s)', activeTasksCount: '{{count}} active task(s)', emptySelectionAllowsAll: 'With no selection, all installed items are allowed.', projectUpdated: 'Project updated', projectUpdateFailed: 'The project could not be updated.', deleteProject: 'Delete project', deleteProjectConfirm: 'Permanently delete this project from Bob Work?', projectDeleteFailed: 'The project could not be deleted.', startProjectConversation: 'Start a conversation', recentTasks: 'Project tasks', projectFiles: 'Project files', allowedResources: 'Project permissions', allAllowed: 'Allow all', untitledTask: 'Untitled task',
  pluginsAndSkills: 'Plugins and skills', plugins: 'Plugins', skills: 'Skills', selectedPlugins: 'Selected plugins', removePlugin: 'Remove {{name}}', selectedCount: '{{count}} selected', noneSelected: 'None selected', done: 'Done', mode: 'Mode', modeAgent: 'Agent', modePlan: 'Planning', modeAsk: 'Ask', scheduleActive: 'Active',
  searchCatalog: 'Search a skill, plugin or integration…', noPlugins: 'No plugins enabled.', noSkills: 'No skills enabled.', noIntegrations: 'No connected integrations.', noPluginMatch: 'No matching plugin.', noSkillMatch: 'No matching skill.', noIntegrationMatch: 'No matching integration.', noModeMatch: 'No matching mode.', integrationConnected: 'Connected', integrationDisconnected: 'Not connected',
  promptPlaceholder: 'Ask Bob to do something…', send: 'Send', attach: 'Add', attachment: 'Attachment', attachFile: 'File', attachPhoto: 'Photo', attachments: 'Attachments', artifacts: 'Created files', interactiveVisualization: 'Interactive visualization', openPreview: 'Open preview', fileChanges: 'File changes', fileCreated: 'Created', fileModified: 'Modified', fileDeleted: 'Deleted', openOrDownload: 'Open or download', download: 'Download', downloadComplete: 'The file is ready to save or share.', artifactFailed: 'Could not retrieve this file.', remove: 'Remove', tools: 'Tools', you: 'You',
  filesCount: '{{count}} file(s)', searchFiles: 'Search files', allFiles: 'All', images: 'Images', textFiles: 'Text', otherFiles: 'Other', noFiles: 'No files', noFilesDesc: 'Documents created by Bob will appear here, regardless of their conversation.', filesLoadFailed: 'Could not load files from Bob Work.', deleteFile: 'Delete file', deleteFileConfirm: 'Permanently delete “{{name}}” from Bob Work?', fileDeleteFailed: 'The file could not be deleted.', saveOrShare: 'Save or share', originProject: 'Project', originConversation: 'Conversation', valid: 'Valid', warning: 'Warning', invalid: 'Invalid', pending: 'Pending review', systemPreviewHint: 'Use the button below to open it in the iOS viewer or save it to Files.', loading: 'Loading…',
  loadingOlder: 'Loading earlier exchanges…', loadingMoreHistory: 'Loading more…', noMessages: 'Send your first prompt.', bobWorking: 'Bob is working…', projectToolsRestricted: 'Tools limited by the project', allToolsAvailable: 'All installed tools are available', sendFailed: 'The prompt could not be sent.', uploadFailed: 'This attachment could not be prepared.', imagePermission: 'Allow photo access to attach a photo.',
  editPrompt: 'Edit', editingPrompt: 'Editing prompt', resendPrompt: 'Resend', cancelEdit: 'Cancel editing', copyMarkdown: 'Copy', copied: 'Markdown copied', shareResponse: 'Share', promptQueue: 'Prompt queue', queuedPrompts: '{{count}} prompt(s) queued', promptQueued: 'Prompt added to the queue', clearQueue: 'Clear', moveUp: 'Move up', moveDown: 'Move down',
  noTasks: 'No activity', noTasksDesc: 'Tasks started in Bob Work will appear here.', taskStarting: 'Starting', taskRunning: 'Running', taskQueued: 'Queued', taskApproval: 'Approval required', taskPaused: 'Paused', taskCompleted: 'Completed', taskFailed: 'Failed', taskCancelled: 'Cancelled', taskExpired: 'Expired', taskDraft: 'Draft', riskLow: 'Low', riskMedium: 'Medium', riskHigh: 'High', riskCritical: 'Critical', eventAnalysis: 'Analyzing', eventContent: 'Content produced', eventError: 'Error', eventHookStarted: 'Preparing', eventMessageStarted: 'Response in progress', eventMessageFinished: 'Response completed', eventRunFinished: 'Run completed', eventText: 'Text generated', eventToolStarted: 'Tool started', eventToolProgress: 'Tool in progress', eventToolFinished: 'Tool completed', eventUsage: 'Usage', eventTaskStarted: 'Task started', eventTaskCompleted: 'Task completed', eventTaskFailed: 'Task failed', eventSubagentStarted: 'Sub-agent started', eventSubagentFinished: 'Sub-agent completed', subagentsRunning: '{{count}} sub-agent(s) running', subagents: '{{count}} sub-agent(s)', subagentFallback: 'Sub-agent', subagentRunning: 'Running', subagentCompleted: 'Completed', subagentFailed: 'Failed', subagentCancelled: 'Stopped',
  tasksTab: 'Tasks', automationsTab: 'Scheduled', taskDetails: 'Task details', taskResult: 'Result', taskErrors: 'Errors', taskTools: 'Tools used', taskRuns: 'Run history', duration: 'Duration', pinTask: 'Pin task', unpinTask: 'Unpin task', noResult: 'No result available.', newAutomation: 'New schedule', noAutomations: 'No schedules', noAutomationsDesc: 'Schedule a recurring task run by Bob Work.', automationName: 'Name', automationInstructions: 'Instructions', frequency: 'Frequency', everyDay: 'Every day', everyWeek: 'Every week', everyMonth: 'Every month', runAt: 'Time', createAutomation: 'Create schedule', pauseAutomation: 'Pause', resumeAutomation: 'Resume', runNow: 'Run now', runHistory: 'History', nextRun: 'Next run: {{date}}', neverRun: 'Never run', noRuns: 'No runs', automationCreated: 'Schedule created', automationFailed: 'Could not update this schedule.',
  liveConnected: 'Live updates active', liveDisconnected: 'Reconnecting live updates…', taskActivity: 'Live activity', noActivityYet: 'Bob is preparing the task…', stopTask: 'Stop', stopTaskConfirm: 'Stop this task on the Mac?', stopFailed: 'Could not stop this task.', approvals: 'Approvals', approveOnce: 'Allow once', approveTask: 'For this task', approveAlways: 'Always allow', deny: 'Deny', approvalFailed: 'Could not save this decision.', risk: 'Risk: {{level}}', retryTask: 'Retry', retryTaskConfirm: 'Retry this task with Bob?', retryFailed: 'The task could not be retried.', taskAwaitingInfo: 'Reply needed', notificationTaskDone: 'Task completed', notificationTaskFailed: 'Task failed', notificationApproval: 'Approval requested', viewDetails: 'View details',
  currentLocation: 'Current location', currentLocationDesc: 'Use my location for nearby searches and as the starting point for routes.', locationEnabled: 'Location enabled', locationDisabled: 'Location disabled', locationRefresh: 'Refresh', locationPermissionDenied: 'Allow location access in your phone settings.', locationUpdateFailed: 'The location could not be sent to Bob Work.', locationPrivacy: 'The location is sent only to your connected Bob Work and used for a relevant map request.',
  remoteConnection: 'Remote connection', connected: 'Connected', server: 'Server', language: 'Language', bobStatus: 'Bob Work status', bobAvailable: 'Bob Shell available', bobUnavailable: 'Bob Shell unavailable', workspaceSettings: 'Bob Work configuration', syncStatus: 'Synchronization', lastSync: 'Last updated: {{date}}', bobcoins: 'Bobcoins', bobcoinsUsed: '{{used}} / {{total}} used', bobcoinsRemaining: '{{remaining}} remaining', bobcoinsUnavailable: 'Usage unavailable', bobcoinsUpdated: 'Updated: {{date}}', sandboxOn: 'Sandbox enabled', sandboxOff: 'Standard project access', permissionPolicy: 'Permission policy', policyAlwaysAsk: 'Always ask', policyAskImportant: 'Ask for important actions', policyAskModifications: 'Ask before changes', policyNeverAsk: 'Never ask', followsBobWork: 'Modes, projects, and execution rules come from this Mac.', disconnect: 'Disconnect', disconnectConfirm: 'Disconnect Bob Mobile from this Mac?', confirm: 'Confirm', back: 'Back', retry: 'Retry', error: 'Error',
  extensions: 'Extensions', manageExtensions: 'Plugins, skills and integrations', extensionsDescription: 'Manage the capabilities installed on this Mac.', integrated: 'Built-in', personal: 'Personal', favorites: 'Favorites', recentlyUsed: 'Recent', all: 'All', enabled: 'Enabled', disabled: 'Disabled', enable: 'Enable', disable: 'Disable', pluginDetails: 'Plugin details', skillDetails: 'Skill details', integrationDetails: 'Integration details', permissions: 'Permissions', capabilities: 'Capabilities', toolsAvailable: 'Available tools', configurationOnMac: 'Configuration on the Mac', configurationOnMacDesc: 'API keys, accounts, and sensitive installations stay protected in Bob Work on the Mac.', configuredOnMac: 'Configured on the Mac', requiresConfiguration: 'Configure on the Mac', noPermissions: 'No additional permissions.', noTools: 'No tools declared.', version: 'Version {{version}}', updateAvailable: 'Version {{version}} available', updatePlugin: 'Update', updating: 'Updating…', pluginUpdated: 'Plugin updated', extensionUpdateFailed: 'The update could not be installed.', extensionLoadFailed: 'Could not load Bob Work extensions.', addFavorite: 'Add to favorites', removeFavorite: 'Remove from favorites', scope: 'Scope', connectedAccount: 'Account: {{account}}', oauthReady: 'Connection available on the Mac', scopeMissing: 'Account permissions are incomplete', sensitiveOnMac: 'Connections and secret entry are only handled on the Mac.', lastUsed: 'Last used: {{date}}', neverUsed: 'Not used yet', noCatalogResults: 'No matching items.', pluginActivationFailed: 'The plugin state could not be changed.', skillActivationFailed: 'The skill state could not be changed.', builtinItem: 'Built-in', personalItem: 'Personal',
  mcpAndApis: 'MCP and APIs', noMcpAndApis: 'No MCP server or API is configured.', databases: 'Databases', noDatabases: 'No database is configured.', microphonePermissionTitle: 'Microphone required', microphonePermission: 'Allow Bob Mobile to use the microphone to record a prompt.', recordingFailed: 'Audio recording failed.', voicePromptFallback: 'Analyze this voice message and respond to my request.', attachmentPromptFallback: 'Analyze the attachments and respond to my request.', voiceRecording: 'Voice message', stopRecording: 'Stop recording', recordVoice: 'Record a voice message', recording: 'Recording', selectedResources: '{{count}} resource(s) selected', importFile: 'Import a file',
  french: 'Français', english: 'English', spanish: 'Español', secureStorage: 'The token is kept in secure storage on this device.', projectCreated: 'Project created', projectCreateFailed: 'Could not create the project.', conversationCreateFailed: 'Could not create the conversation.',
}

const es: typeof fr = {
  bobCommands: 'Comandos de Bob', addToPrompt: 'Añadir al prompt',
  appName: 'Bob Mobile', disconnected: 'Desconectado', connectTitle: 'Conectar Bob Work', connectDesc: 'En Bob Work, abra Ajustes → Control remoto, actívelo y copie el enlace de Cloudflare.',
  connectionLink: 'Enlace de conexión', connectionPlaceholder: 'Pegue el enlace seguro de Bob Work', connect: 'Conectar', connecting: 'Conectando…', invalidLink: 'Este enlace de conexión no es válido.', missingToken: 'El enlace no contiene un token de acceso.', connectionFailed: 'No se pudo conectar con Bob Work.', connectionTimeout: 'Bob Work no respondió. El intento se detuvo después de 10 segundos.', apiUnavailable: 'El túnel responde, pero la API de Bob Work no está disponible.', connectionExpired: 'Este enlace ha caducado o su token fue revocado. Copie el enlace actual desde Bob Work.', updateConnection: 'Nuevo enlace',
  conversations: 'Conversaciones', projects: 'Proyectos', activity: 'Actividad', files: 'Archivos', settings: 'Ajustes', newConversation: 'Nueva conversación', noConversations: 'No hay conversaciones', noConversationsDesc: 'Cree una conversación para empezar a controlar Bob Work.', syncRequiredTitle: 'Vuelva a conectar Bob Work', syncRequiredDesc: 'El historial se recargará directamente desde la base SQLite del Mac tras la reconexión.', searchConversations: 'Buscar en el historial', history: 'Historial', syncUnavailable: 'La sincronización no está disponible — toque para reintentar.',
  allProjects: 'Todos los proyectos', noProject: 'Sin proyecto', conversationTitle: 'Título', conversationTitlePlaceholder: 'Nueva conversación', create: 'Crear', cancel: 'Cancelar', active: 'En curso', queued: 'En espera', refresh: 'Actualizar',
  recent: 'Recientes', completed: 'Terminadas', scheduled: 'Programadas', archived: 'Archivadas', archivedChats: 'Chats archivados', archivedChatsDescription: 'Los chats archivados se gestionan aquí sin poder abrirlos.', noArchivedChats: 'No hay chats archivados.', archivedChatsLoadFailed: 'No se pudieron cargar los chats archivados.', archive: 'Archivar', restore: 'Restaurar', pin: 'Fijar', unpin: 'Desfijar', moreActions: 'Más acciones', conversationActions: 'Gestionar conversación', moveToProject: 'Mover a un proyecto', saveChanges: 'Guardar', delete: 'Eliminar', deleteConversation: 'Eliminar conversación', deleteConversationConfirm: '¿Eliminar definitivamente esta conversación de Bob Work?', conversationUpdateFailed: 'No se pudo modificar la conversación.', conversationDeleteFailed: 'No se pudo eliminar la conversación.',
  newProject: 'Nuevo proyecto', editProject: 'Editar proyecto', openProject: 'Abrir proyecto', projectName: 'Nombre del proyecto', projectNamePlaceholder: 'Ej. Rediseño del sitio', description: 'Descripción', descriptionPlaceholder: 'Contexto del proyecto', objective: 'Objetivo', objectivePlaceholder: 'Resultado esperado', customInstructions: 'Instrucciones del proyecto', customInstructionsPlaceholder: 'Reglas y contexto específicos del proyecto', projectLanguage: 'Idioma del proyecto', automatic: 'Automático', memory: 'Memoria del proyecto', memoryOn: 'Activada', memoryOff: 'Desactivada', defaultMode: 'Modo predeterminado', integrations: 'Integraciones', noProjects: 'No hay proyectos', noProjectsDesc: 'Cree su primer proyecto Bob Work.', openConversations: 'Ver conversaciones', conversationsCount: '{{count}} conversación(es)', activeTasksCount: '{{count}} tarea(s) activa(s)', emptySelectionAllowsAll: 'Sin selección, se permiten todos los elementos instalados.', projectUpdated: 'Proyecto actualizado', projectUpdateFailed: 'No se pudo modificar el proyecto.', deleteProject: 'Eliminar proyecto', deleteProjectConfirm: '¿Eliminar definitivamente este proyecto de Bob Work?', projectDeleteFailed: 'No se pudo eliminar el proyecto.', startProjectConversation: 'Iniciar una conversación', recentTasks: 'Tareas del proyecto', projectFiles: 'Archivos del proyecto', allowedResources: 'Permisos del proyecto', allAllowed: 'Permitir todo', untitledTask: 'Tarea sin título',
  pluginsAndSkills: 'Plugins y skills', plugins: 'Plugins', skills: 'Skills', selectedPlugins: 'Plugins seleccionados', removePlugin: 'Quitar {{name}}', selectedCount: '{{count}} seleccionado(s)', noneSelected: 'Ninguno seleccionado', done: 'Listo', mode: 'Modo', modeAgent: 'Agente', modePlan: 'Planificación', modeAsk: 'Pregunta', scheduleActive: 'Activo',
  searchCatalog: 'Buscar un skill, plugin o integración…', noPlugins: 'No hay plugins activados.', noSkills: 'No hay skills activados.', noIntegrations: 'No hay integraciones conectadas.', noPluginMatch: 'No hay plugins coincidentes.', noSkillMatch: 'No hay skills coincidentes.', noIntegrationMatch: 'No hay integraciones coincidentes.', noModeMatch: 'No hay modos coincidentes.', integrationConnected: 'Conectada', integrationDisconnected: 'No conectada',
  promptPlaceholder: 'Pídale algo a Bob…', send: 'Enviar', attach: 'Añadir', attachment: 'Adjunto', attachFile: 'Archivo', attachPhoto: 'Foto', attachments: 'Adjuntos', artifacts: 'Archivos creados', interactiveVisualization: 'Visualización interactiva', openPreview: 'Abrir vista previa', fileChanges: 'Cambios en archivos', fileCreated: 'Creado', fileModified: 'Modificado', fileDeleted: 'Eliminado', openOrDownload: 'Abrir o descargar', download: 'Descargar', downloadComplete: 'El archivo está listo para guardar o compartir.', artifactFailed: 'No se pudo recuperar este archivo.', remove: 'Quitar', tools: 'Herramientas', you: 'Tú',
  filesCount: '{{count}} archivo(s)', searchFiles: 'Buscar archivos', allFiles: 'Todos', images: 'Imágenes', textFiles: 'Texto', otherFiles: 'Otros', noFiles: 'No hay archivos', noFilesDesc: 'Los documentos creados por Bob aparecerán aquí, independientemente de su conversación.', filesLoadFailed: 'No se pudieron cargar los archivos de Bob Work.', deleteFile: 'Eliminar archivo', deleteFileConfirm: '¿Eliminar definitivamente «{{name}}» de Bob Work?', fileDeleteFailed: 'No se pudo eliminar el archivo.', saveOrShare: 'Guardar o compartir', originProject: 'Proyecto', originConversation: 'Conversación', valid: 'Válido', warning: 'Advertencia', invalid: 'No válido', pending: 'Pendiente de validar', systemPreviewHint: 'Use el botón de abajo para abrirlo en el visor de iOS o guardarlo en Archivos.', loading: 'Cargando…',
  loadingOlder: 'Cargando intercambios anteriores…', loadingMoreHistory: 'Cargando más…', noMessages: 'Envíe su primer prompt.', bobWorking: 'Bob está trabajando…', projectToolsRestricted: 'Herramientas limitadas por el proyecto', allToolsAvailable: 'Todas las herramientas instaladas están disponibles', sendFailed: 'No se pudo enviar el prompt.', uploadFailed: 'No se pudo preparar este adjunto.', imagePermission: 'Permita el acceso a las fotos para adjuntar una foto.',
  editPrompt: 'Editar', editingPrompt: 'Editando el prompt', resendPrompt: 'Reenviar', cancelEdit: 'Cancelar edición', copyMarkdown: 'Copiar', copied: 'Markdown copiado', shareResponse: 'Compartir', promptQueue: 'Cola de prompts', queuedPrompts: '{{count}} prompt(s) en cola', promptQueued: 'Prompt añadido a la cola', clearQueue: 'Vaciar', moveUp: 'Subir', moveDown: 'Bajar',
  noTasks: 'Sin actividad', noTasksDesc: 'Las tareas iniciadas en Bob Work aparecerán aquí.', taskStarting: 'Iniciando', taskRunning: 'En curso', taskQueued: 'En espera', taskApproval: 'Autorización necesaria', taskPaused: 'En pausa', taskCompleted: 'Terminada', taskFailed: 'Fallida', taskCancelled: 'Cancelada', taskExpired: 'Expirada', taskDraft: 'Borrador', riskLow: 'Bajo', riskMedium: 'Medio', riskHigh: 'Alto', riskCritical: 'Crítico', eventAnalysis: 'Analizando', eventContent: 'Contenido producido', eventError: 'Error', eventHookStarted: 'Preparando', eventMessageStarted: 'Respuesta en curso', eventMessageFinished: 'Respuesta terminada', eventRunFinished: 'Ejecución terminada', eventText: 'Texto generado', eventToolStarted: 'Herramienta iniciada', eventToolProgress: 'Herramienta en curso', eventToolFinished: 'Herramienta terminada', eventUsage: 'Uso', eventTaskStarted: 'Tarea iniciada', eventTaskCompleted: 'Tarea terminada', eventTaskFailed: 'Tarea fallida', eventSubagentStarted: 'Subagente iniciado', eventSubagentFinished: 'Subagente terminado', subagentsRunning: '{{count}} subagente(s) en curso', subagents: '{{count}} subagente(s)', subagentFallback: 'Subagente', subagentRunning: 'En curso', subagentCompleted: 'Terminado', subagentFailed: 'Fallido', subagentCancelled: 'Detenido',
  tasksTab: 'Tareas', automationsTab: 'Programado', taskDetails: 'Detalles de la tarea', taskResult: 'Resultado', taskErrors: 'Errores', taskTools: 'Herramientas utilizadas', taskRuns: 'Historial de ejecuciones', duration: 'Duración', pinTask: 'Fijar tarea', unpinTask: 'Desfijar tarea', noResult: 'No hay resultado disponible.', newAutomation: 'Nueva planificación', noAutomations: 'No hay planificaciones', noAutomationsDesc: 'Programe una tarea recurrente ejecutada por Bob Work.', automationName: 'Nombre', automationInstructions: 'Instrucciones', frequency: 'Frecuencia', everyDay: 'Cada día', everyWeek: 'Cada semana', everyMonth: 'Cada mes', runAt: 'Hora', createAutomation: 'Crear planificación', pauseAutomation: 'Pausar', resumeAutomation: 'Reactivar', runNow: 'Ejecutar ahora', runHistory: 'Historial', nextRun: 'Próxima ejecución: {{date}}', neverRun: 'Nunca ejecutada', noRuns: 'Sin ejecuciones', automationCreated: 'Planificación creada', automationFailed: 'No se pudo actualizar esta planificación.',
  liveConnected: 'Actualizaciones en tiempo real', liveDisconnected: 'Reconectando las actualizaciones…', taskActivity: 'Actividad en directo', noActivityYet: 'Bob está preparando la tarea…', stopTask: 'Detener', stopTaskConfirm: '¿Detener esta tarea en el Mac?', stopFailed: 'No se pudo detener esta tarea.', approvals: 'Autorizaciones', approveOnce: 'Autorizar una vez', approveTask: 'Para esta tarea', approveAlways: 'Autorizar siempre', deny: 'Rechazar', approvalFailed: 'No se pudo guardar esta decisión.', risk: 'Riesgo: {{level}}', retryTask: 'Reintentar', retryTaskConfirm: '¿Reintentar esta tarea con Bob?', retryFailed: 'No se pudo reintentar la tarea.', taskAwaitingInfo: 'Respuesta necesaria', notificationTaskDone: 'Tarea terminada', notificationTaskFailed: 'Tarea fallida', notificationApproval: 'Autorización solicitada', viewDetails: 'Ver detalles',
  currentLocation: 'Ubicación actual', currentLocationDesc: 'Usar mi ubicación para búsquedas cercanas y como inicio de rutas.', locationEnabled: 'Ubicación autorizada', locationDisabled: 'Ubicación desactivada', locationRefresh: 'Actualizar', locationPermissionDenied: 'Permita la ubicación en los ajustes del teléfono.', locationUpdateFailed: 'No se pudo enviar la ubicación a Bob Work.', locationPrivacy: 'La ubicación solo se envía a su Bob Work conectado y se usa para una solicitud cartográfica pertinente.',
  remoteConnection: 'Conexión remota', connected: 'Conectado', server: 'Servidor', language: 'Idioma', bobStatus: 'Estado de Bob Work', bobAvailable: 'Bob Shell disponible', bobUnavailable: 'Bob Shell no disponible', workspaceSettings: 'Configuración de Bob Work', syncStatus: 'Sincronización', lastSync: 'Última actualización: {{date}}', bobcoins: 'Bobcoins', bobcoinsUsed: '{{used}} / {{total}} utilizados', bobcoinsRemaining: '{{remaining}} restantes', bobcoinsUnavailable: 'Consumo no disponible', bobcoinsUpdated: 'Actualizado: {{date}}', sandboxOn: 'Entorno aislado activado', sandboxOff: 'Acceso estándar al proyecto', permissionPolicy: 'Política de autorización', policyAlwaysAsk: 'Preguntar siempre', policyAskImportant: 'Preguntar para acciones importantes', policyAskModifications: 'Preguntar antes de modificar', policyNeverAsk: 'No preguntar nunca', followsBobWork: 'Los modos, proyectos y reglas de ejecución provienen de este Mac.', disconnect: 'Desconectar', disconnectConfirm: '¿Desconectar Bob Mobile de este Mac?', confirm: 'Confirmar', back: 'Volver', retry: 'Reintentar', error: 'Error',
  extensions: 'Extensiones', manageExtensions: 'Plugins, skills e integraciones', extensionsDescription: 'Gestione las capacidades instaladas en este Mac.', integrated: 'Integrados', personal: 'Personales', favorites: 'Favoritos', recentlyUsed: 'Recientes', all: 'Todos', enabled: 'Activado', disabled: 'Desactivado', enable: 'Activar', disable: 'Desactivar', pluginDetails: 'Detalles del plugin', skillDetails: 'Detalles del skill', integrationDetails: 'Detalles de la integración', permissions: 'Permisos', capabilities: 'Capacidades', toolsAvailable: 'Herramientas disponibles', configurationOnMac: 'Configuración en el Mac', configurationOnMacDesc: 'Las claves API, cuentas e instalaciones sensibles permanecen protegidas en Bob Work en el Mac.', configuredOnMac: 'Configurada en el Mac', requiresConfiguration: 'Configurar en el Mac', noPermissions: 'Sin permisos adicionales.', noTools: 'No hay herramientas declaradas.', version: 'Versión {{version}}', updateAvailable: 'Versión {{version}} disponible', updatePlugin: 'Actualizar', updating: 'Actualizando…', pluginUpdated: 'Plugin actualizado', extensionUpdateFailed: 'No se pudo instalar la actualización.', extensionLoadFailed: 'No se pudieron cargar las extensiones de Bob Work.', addFavorite: 'Añadir a favoritos', removeFavorite: 'Quitar de favoritos', scope: 'Ámbito', connectedAccount: 'Cuenta: {{account}}', oauthReady: 'Conexión disponible en el Mac', scopeMissing: 'Los permisos de la cuenta están incompletos', sensitiveOnMac: 'La conexión y la entrada de secretos solo se realizan en el Mac.', lastUsed: 'Último uso: {{date}}', neverUsed: 'Aún no utilizado', noCatalogResults: 'No hay elementos coincidentes.', pluginActivationFailed: 'No se pudo cambiar el estado del plugin.', skillActivationFailed: 'No se pudo cambiar el estado del skill.', builtinItem: 'Integrado', personalItem: 'Personal',
  mcpAndApis: 'MCP y APIs', noMcpAndApis: 'No hay ningún servidor MCP o API configurado.', databases: 'Bases de datos', noDatabases: 'No hay ninguna base de datos configurada.', microphonePermissionTitle: 'Se requiere micrófono', microphonePermission: 'Permita que Bob Mobile use el micrófono para grabar un prompt.', recordingFailed: 'La grabación de audio ha fallado.', voicePromptFallback: 'Analiza este mensaje de voz y responde a mi solicitud.', attachmentPromptFallback: 'Analiza los archivos adjuntos y responde a mi solicitud.', voiceRecording: 'Mensaje de voz', stopRecording: 'Detener la grabación', recordVoice: 'Grabar un mensaje de voz', recording: 'Grabación', selectedResources: '{{count}} recurso(s) seleccionado(s)', importFile: 'Importar un archivo',
  french: 'Français', english: 'English', spanish: 'Español', secureStorage: 'El token se guarda en el almacenamiento seguro del dispositivo.', projectCreated: 'Proyecto creado', projectCreateFailed: 'No se pudo crear el proyecto.', conversationCreateFailed: 'No se pudo crear la conversación.',
}

export type TranslationKey = keyof typeof fr
export const catalogs = { fr, en, es }

export const languageLocales: Record<Language, string> = {
  fr: 'fr-FR',
  en: 'en-US',
  es: 'es-ES',
}

export function formatDateTime(value: string | number | Date, language: Language): string {
  const date = new Date(value)
  return Number.isNaN(date.getTime()) ? '' : new Intl.DateTimeFormat(languageLocales[language], {
    dateStyle: 'medium',
    timeStyle: 'short',
  }).format(date)
}

export function formatDate(value: string | number | Date, language: Language): string {
  const date = new Date(value)
  return Number.isNaN(date.getTime()) ? '' : new Intl.DateTimeFormat(languageLocales[language], {
    dateStyle: 'medium',
  }).format(date)
}

export function formatTime(value: string | number | Date, language: Language): string {
  const date = new Date(value)
  return Number.isNaN(date.getTime()) ? '' : new Intl.DateTimeFormat(languageLocales[language], {
    hour: '2-digit',
    minute: '2-digit',
    hourCycle: 'h23',
  }).format(date)
}

export function formatNumber(value: number, language: Language, maximumFractionDigits = 1): string {
  return new Intl.NumberFormat(languageLocales[language], { maximumFractionDigits }).format(value)
}

export function translate(language: Language, key: TranslationKey, params?: Record<string, string | number>): string {
  let value = catalogs[language][key] ?? fr[key] ?? key
  if (params) {
    value = value.replace(/\{\{(\w+)\}\}/g, (_, name: string) => String(params[name] ?? `{{${name}}}`))
  }
  return value
}

export function deviceLanguage(): Language {
  const locale = Intl.DateTimeFormat().resolvedOptions().locale.toLowerCase()
  if (locale.startsWith('es')) return 'es'
  if (locale.startsWith('en')) return 'en'
  return 'fr'
}
